// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"mini_tiktok/apps/user/internal/logic"
	"mini_tiktok/apps/user/internal/svc"
	"mini_tiktok/apps/user/user"
)

type UserRPCServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRPCServer
}

func NewUserRPCServer(svcCtx *svc.ServiceContext) *UserRPCServer {
	return &UserRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRPCServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserRPCServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserRPCServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserRPCServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoReq) (*user.GetUserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
