// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.1
// source: like.proto

package like

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LikeRPC_LikeAction_FullMethodName = "/like.LikeRPC/LikeAction"
)

// LikeRPCClient is the client API for LikeRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeRPCClient interface {
	LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error)
}

type likeRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeRPCClient(cc grpc.ClientConnInterface) LikeRPCClient {
	return &likeRPCClient{cc}
}

func (c *likeRPCClient) LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error) {
	out := new(LikeActionResp)
	err := c.cc.Invoke(ctx, LikeRPC_LikeAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeRPCServer is the server API for LikeRPC service.
// All implementations must embed UnimplementedLikeRPCServer
// for forward compatibility
type LikeRPCServer interface {
	LikeAction(context.Context, *LikeActionReq) (*LikeActionResp, error)
	mustEmbedUnimplementedLikeRPCServer()
}

// UnimplementedLikeRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLikeRPCServer struct {
}

func (UnimplementedLikeRPCServer) LikeAction(context.Context, *LikeActionReq) (*LikeActionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeAction not implemented")
}
func (UnimplementedLikeRPCServer) mustEmbedUnimplementedLikeRPCServer() {}

// UnsafeLikeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeRPCServer will
// result in compilation errors.
type UnsafeLikeRPCServer interface {
	mustEmbedUnimplementedLikeRPCServer()
}

func RegisterLikeRPCServer(s grpc.ServiceRegistrar, srv LikeRPCServer) {
	s.RegisterService(&LikeRPC_ServiceDesc, srv)
}

func _LikeRPC_LikeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeRPCServer).LikeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeRPC_LikeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeRPCServer).LikeAction(ctx, req.(*LikeActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LikeRPC_ServiceDesc is the grpc.ServiceDesc for LikeRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikeRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "like.LikeRPC",
	HandlerType: (*LikeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LikeAction",
			Handler:    _LikeRPC_LikeAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "like.proto",
}
