// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"mini_tiktok/apps/like/internal/logic"
	"mini_tiktok/apps/like/internal/svc"
	"mini_tiktok/apps/like/like"
)

type LikeRPCServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedLikeRPCServer
}

func NewLikeRPCServer(svcCtx *svc.ServiceContext) *LikeRPCServer {
	return &LikeRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeRPCServer) LikeAction(ctx context.Context, in *like.LikeActionReq) (*like.LikeActionResp, error) {
	l := logic.NewLikeActionLogic(ctx, s.svcCtx)
	return l.LikeAction(in)
}
