// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"mini_tiktok/apps/like/internal/logic"
	"mini_tiktok/apps/like/internal/svc"
	"mini_tiktok/apps/like/like"
)

type VideoRPCServer struct {
	svcCtx *svc.ServiceContext
	like.UnimplementedVideoRPCServer
}

func NewVideoRPCServer(svcCtx *svc.ServiceContext) *VideoRPCServer {
	return &VideoRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoRPCServer) LikeAction(ctx context.Context, in *like.LikeActionRequest) (*like.LikeActionResponse, error) {
	l := logic.NewLikeActionLogic(ctx, s.svcCtx)
	return l.LikeAction(in)
}
