// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"mini_tiktok/apps/video/internal/logic"
	"mini_tiktok/apps/video/internal/svc"
	"mini_tiktok/apps/video/video"
)

type VideoRPCServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoRPCServer
}

func NewVideoRPCServer(svcCtx *svc.ServiceContext) *VideoRPCServer {
	return &VideoRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoRPCServer) GetFeed(ctx context.Context, in *video.GetFeedRequest) (*video.GetFeedResponse, error) {
	l := logic.NewGetFeedLogic(ctx, s.svcCtx)
	return l.GetFeed(in)
}

func (s *VideoRPCServer) GetPublishVideoList(ctx context.Context, in *video.GetPublishVideoListRequest) (*video.GetPublishVideoListResponse, error) {
	l := logic.NewGetPublishVideoListLogic(ctx, s.svcCtx)
	return l.GetPublishVideoList(in)
}

func (s *VideoRPCServer) PublishVideo(ctx context.Context, in *video.PublishVideoRequest) (*video.PublishVideoResponse, error) {
	l := logic.NewPublishVideoLogic(ctx, s.svcCtx)
	return l.PublishVideo(in)
}
