// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package likerpc

import (
	"context"

	"mini_tiktok/apps/like/like"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LikeActionReq  = like.LikeActionReq
	LikeActionResp = like.LikeActionResp

	LikeRPC interface {
		LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error)
	}

	defaultLikeRPC struct {
		cli zrpc.Client
	}
)

func NewLikeRPC(cli zrpc.Client) LikeRPC {
	return &defaultLikeRPC{
		cli: cli,
	}
}

func (m *defaultLikeRPC) LikeAction(ctx context.Context, in *LikeActionReq, opts ...grpc.CallOption) (*LikeActionResp, error) {
	client := like.NewLikeRPCClient(m.cli.Conn())
	return client.LikeAction(ctx, in, opts...)
}
