// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package videorpc

import (
	"context"

	"mini_tiktok/apps/like/like"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LikeActionRequest  = like.LikeActionRequest
	LikeActionResponse = like.LikeActionResponse

	VideoRPC interface {
		LikeAction(ctx context.Context, in *LikeActionRequest, opts ...grpc.CallOption) (*LikeActionResponse, error)
	}

	defaultVideoRPC struct {
		cli zrpc.Client
	}
)

func NewVideoRPC(cli zrpc.Client) VideoRPC {
	return &defaultVideoRPC{
		cli: cli,
	}
}

func (m *defaultVideoRPC) LikeAction(ctx context.Context, in *LikeActionRequest, opts ...grpc.CallOption) (*LikeActionResponse, error) {
	client := like.NewVideoRPCClient(m.cli.Conn())
	return client.LikeAction(ctx, in, opts...)
}
