Name: app
Host: 0.0.0.0
Port: 8889
Timeout: 100000

Log:
  ServiceName: app
  Mode: console
  Level: info
  Encoding: plain

UserRpcConf:
  Etcd:
    Hosts:
      - 0.0.0.0:2379
    Key: user.rpc
  Timeout: 100000