Name: app
Host: 0.0.0.0
Port: 8889
Timeout: 10000000
Mode: dev

Log:
  ServiceName: app
  Mode: console
  Level: debug
  Encoding: plain

JwtAuth:
  AccessSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  AccessExpire: 604800
  RefreshSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  RefreshExpire: 2592000
  RefreshAfter: 604800


UserRpcConf:
  Etcd:
    Hosts:
      - 0.0.0.0:2379
    Key: user.rpc
  Timeout: 10000000

Oss:
  Endpoint: oss-cn-shanghai.aliyuncs.com
  AccessKeyId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  AccessKeySecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  VideoBucket: minitiktokvideo