// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userrpc

import (
	"context"

	"mini_tiktok/apps/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = user.Request
	Response = user.Response

	UserRPC interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserRPC struct {
		cli zrpc.Client
	}
)

func NewUserRPC(cli zrpc.Client) UserRPC {
	return &defaultUserRPC{
		cli: cli,
	}
}

func (m *defaultUserRPC) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserRPCClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
