// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  int64  `json:"total_favorited"`
	FavoriteCount   int64  `json:"favorited_count"`
	WorkCount       int64  `json:"work_count"`
}

type HelloReq struct {
	Name string `json:"name"`
}

type HelloResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type RegisterReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserID     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
}

type UserInfoReq struct {
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoResp struct {
	User       User   `json:"user"`
}
