// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  int64  `json:"total_favorited"`
	FavoriteCount   int64  `json:"favorited_count"`
	WorkCount       int64  `json:"work_count"`
}

type HelloReq struct {
	Name string `json:"name"`
}

type HelloResp struct {
	StatusCode int    `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type RegisterReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}

type LoginReq struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
}

type UserInfoReq struct {
	UserID int64 `form:"user_id"`
}

type UserInfoResp struct {
	User User `json:"user"`
}

type VideoInfo struct {
	Id            int64  `json:"id"`
	AuthorId      int64  `json:"author_id"`
	Title         string `json:"title"`
	PlayUrl       string `json:"play_url"`
	CoverUrl      string `json:"cover_url"`
	FavoriteCount int64  `json:"favorite_count"`
	CommentCount  int64  `json:"comment_count"`
	IsFavorite    bool   `json:"is_favorite"`
	PublishTime   int64  `json:"publish_time"`
}

type FeedReq struct {
	LastTime int64 `json:"latest_time"`
}

type FeedResp struct {
	NextTime  int64       `json:"next_time"`
	VideoList []VideoInfo `json:"video_list"`
}

type VideoListReq struct {
	UserId   int64 `json:"user_id"`
	Cursor   int64 `json:"cursor"`
	PageSize int64 `json:"page_size"`
	SortType int32 `json:"sort_type"`
	VideoId  int64 `json:"video_id"`
}

type VideoListResp struct {
	VideoList []VideoInfo `json:"video_list"`
	Cursor    int64       `json:"cursor"`
	IsEnd     bool        `json:"is_end"`
	VideoId   int64       `json:"video_id"`
}

type PublishVideoReq struct {
	SaveFile string `json:"save_file"`
	Title    string `json:"title"`
}

type PublishVideoResp struct {
}

type LikeActionReq struct {
	UserId     int64 `json:"user_id"`
	VideoId    int64 `json:"video_id"`
	ActionType int32 `json:"action_type"`
}

type LikeActionResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}
